## Basic Configuration

baseurl = "https://nick.rw/"
builddrafts = false
canonifyurls = false
languageCode = "en-GB"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Nicholas Robinson-Wall"
title = "Nicholas Robinson-Wall"

theme = "hugo-goa"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Nicholas Robinson-Wall"
intro = "Payments Engineer // London"
description = "Building a bank @ [Monzo](https://monzo.com/). Previously [Osper](https://osper.com/), [Mendeley](https://mendeley.com/)"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Nicholas Robinson-Wall's professional profile"
keywords = "linux,sysadmin,systems,administrator,backend,engineer,golang,go,python,devops,cv,resunme"

## Social Accounts
[params.social]
github = "nickrw"
linkedin = "robinsonwall"
keybase = "nickrw"
email = "cv@nick.rw"

## Extras
[params.extra]
copyright = "Â© 2017. Nicholas Robinson-Wall. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true
